### ISSUE TITLE
Undefined when seen as not-logged in user

### ISSUE THREAD

**Issue by mudrd8mz** [dpalou/moodle-filter_applink#4]
When visiting a link like this
```
<a href="https://example.com/course/view.php?id=2" data-app-link="" data-username="">Click me</a>
```
as an anonymous (not logged in) user, I get:

```
Undefined property: stdClass::$username in .../filter/applink/filter.php on line 107
```

**Comment by dpalou** [comment]
Thanks David,

nice catch! I added a new commit to fix this:

https://github.com/dpalou/moodle-filter_applink/commit/22e55e48fe25162edf38852547375966b11bc9f3
